name: CI - Pact PoC

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-pact:
    runs-on: ubuntu-latest

    env:
      PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      GIT_SHA: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm install

      # -------------------------------
      # Install Pact CLI (standalone)
      # -------------------------------
      - name: Install Pact CLI
        run: |
          mkdir -p $HOME/pact
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.82/pact-1.88.82-linux-x86_64.tar.gz
          tar -xzf pact-1.88.82-linux-x86_64.tar.gz -C $HOME/pact
          echo "$HOME/pact/pact/bin" >> $GITHUB_PATH

      - name: Run consumer tests
        run: npm run test:consumer

      - name: Publish pacts to Pactflow
        if: github.ref == 'refs/heads/main'
        run: |
          pact-broker publish consumer/pacts \
            --consumer-app-version="$GIT_SHA" \
            --branch="$GIT_BRANCH" \
            --broker-base-url="$PACT_BROKER_BASE_URL" \
            --broker-token="$PACT_BROKER_TOKEN"

      - name: Run provider verification tests
        env:
          PROVIDER_VERSION: ${{ github.sha }}
          PROVIDER_BRANCH: ${{ github.ref_name }}
          CONSUMER_BRANCH: "main"
        run: npm run test:provider