name: Provider CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  provider-tests-and-verify:
    runs-on: ubuntu-latest

    env:
      PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      PROVIDER_VERSION: ${{ github.sha }}
      PROVIDER_BRANCH: ${{ github.ref_name }}
      CONSUMER_BRANCH: "main"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (monorepo)
        run: npm install

      # Provider verification → PactFlow'dan kontrat çekip verify eder
      - name: Run provider verification tests
        run: npm run test:provider